=== bubu03/mvp4g/xsd/mvp4g-conf.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="boolean">
		<xs:restriction base="xs:boolean">
			<xs:pattern value="true|false" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="logLevel">
		<xs:restriction base="xs:string">
			<xs:pattern value="SIMPLE|DETAILED" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="package">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="className">
		<xs:restriction base="xs:string">
			<xs:pattern value="\.?[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="javaClass">
		<xs:restriction base="xs:string">
		    <xs:pattern value="([a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)*)" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="javaClassArray">
		<xs:restriction base="xs:string">
		    <xs:pattern value="([a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)*)(\s?,\s?([a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)*))*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="javaClassArrayOptional">
		<xs:restriction base="xs:string">
		    <xs:pattern value="([a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)*)(\s?,\s?([a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)*))*|.{0}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="name">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z][a-zA-Z0-9_]*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="nameOptional">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z][a-zA-Z0-9_]*|.{0}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="nameArray">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z][a-zA-Z0-9_]*(\s?,\s?[a-zA-Z][a-zA-Z0-9_]*)*" />
		</xs:restriction>
	</xs:simpleType>
	

	<xs:attributeGroup name="simpleMpv4gElement">
		<xs:attribute name="name" type="name" use="required" />
		<xs:attribute name="class" type="className" use="required" />
	</xs:attributeGroup>

	<xs:attributeGroup name="mvp4gElementWithServices">
		<xs:attributeGroup ref="simpleMpv4gElement" />
		<xs:attribute name="services" type="nameArray" use="optional" />
	</xs:attributeGroup>
	

	<xs:element name="views">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="view" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="services">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="service" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="childModules">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="childModule" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
			<xs:attribute name="beforeEvent" type="name" use="optional" />
			<xs:attribute name="afterEvent" type="name" use="optional" />
			<xs:attribute name="errorEvent" type="name" use="optional" />
		</xs:complexType>
	</xs:element>
			
	<xs:element name="childModule">
		<xs:complexType>
		    <xs:attributeGroup ref="simpleMpv4gElement" />			
			<xs:attribute name="async" type="xs:boolean" use="optional" />
			<xs:attribute name="autoDisplay" type="xs:boolean" use="optional" />
			<xs:attribute name="eventToDisplayView" type="name" use="optional" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="history">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="converter" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
			<xs:attribute name="initEvent" type="name" use="optional" />
			<xs:attribute name="notFoundEvent" type="name" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="presenters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="presenter" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="eventHandlers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="eventHandler" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="events">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="event" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="converter">
		<xs:complexType>
			<xs:attributeGroup ref="mvp4gElementWithServices" />
			<xs:attribute name="convertParams" type="boolean" use="optional" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="filters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="filter" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
			<xs:attribute name="afterHistory" type="boolean" use="optional" />
			<xs:attribute name="filterStart" type="boolean" use="optional" />
			<xs:attribute name="filterForward" type="boolean" use="optional" />
			<xs:attribute name="forceFilters" type="boolean" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="event">
		<xs:complexType>
			<xs:attribute name="handlers" type="nameArray" use="optional" />
			<xs:attribute name="type" type="name" use="required" />
			<xs:attribute name="calledMethod" type="name" use="optional" />
			<xs:attribute name="eventObjectClass" type="javaClassArrayOptional" use="optional" />
			<xs:attribute name="history" type="name" use="optional" />
			<xs:attribute name="historyName" type="nameOptional" use="optional" />
			<xs:attribute name="multiple" type="boolean" use="optional" />
			<xs:attribute name="forwardToParent" type="xs:boolean" use="optional" />
			<xs:attribute name="modulesToLoad" type="nameArray" use="optional" />
			<xs:attribute name="activate" type="nameArray" use="optional" />
			<xs:attribute name="deactivate" type="nameArray" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="mvp4g">
		<xs:complexType mixed="true">
			<xs:all>
				<xs:element ref="events" minOccurs="0"  />
				<xs:element ref="history" minOccurs="0" />
				<xs:element ref="presenters" />
				<xs:element ref="services" minOccurs="0" />
				<xs:element ref="start" minOccurs="0"  />
				<xs:element ref="views" minOccurs="0"  />
				<xs:element ref="childModules" minOccurs="0"  />
				<xs:element ref="debug" minOccurs="0"  />
				<xs:element ref="gin" minOccurs="0"  />
				<xs:element ref="filters" minOccurs="0"  />
				<xs:element ref="eventHandlers" minOccurs="0"  />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="debug">
		<xs:complexType>
			<xs:attribute name="logLevel" type="logLevel" use="optional" />
			<xs:attribute name="logger" type="javaClass" use="optional" />			
		</xs:complexType>
	</xs:element>
	
	<xs:element name="filter">
		<xs:complexType>
			<xs:attributeGroup ref="simpleMpv4gElement" />			
		</xs:complexType>
	</xs:element>

	<xs:element name="presenter">
		<xs:complexType>
			<xs:attributeGroup ref="mvp4gElementWithServices" />
			<xs:attribute name="multiple" type="boolean" use="optional" />
			<xs:attribute name="view" type="name" use="required" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="eventHandler">
		<xs:complexType>
			<xs:attributeGroup ref="mvp4gElementWithServices" />
			<xs:attribute name="multiple" type="boolean" use="optional" />			
		</xs:complexType>
	</xs:element>
	
	<xs:element name="gin">
		<xs:complexType>
			<xs:attribute name="modules" type="javaClassArray" use="required" />
		</xs:complexType>
	</xs:element>	

	<xs:element name="service">
		<xs:complexType>
			<xs:attributeGroup ref="simpleMpv4gElement" />
			<xs:attribute name="path" type="xs:string" use="optional" />
			<xs:attribute name="generatedClassName" type="className" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="start">
		<xs:complexType>
			<xs:attribute name="view" type="name" use="required" />
			<xs:attribute name="eventType" type="name" use="optional" />
			<xs:attribute name="forwardEventType" type="name" use="optional" />
			<xs:attribute name="history" type="boolean" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="view">
		<xs:complexType>
			<xs:attributeGroup ref="simpleMpv4gElement" />
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== bubu03/mvp4g/sources/src/test/resources/mvp4g-conf.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<mvp4g xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://mvp4g.googlecode.com/svn/tags/mvp4g-1.0.0/xsd/mvp4g-conf.xsd">

	<debug />

	<filters afterHistory="true" filterForward="false">
		<filter name="filter1"
			class="com.mvp4g.example.client.company.CompanyEventFilter" />
		<filter name="filter2"
			class="com.mvp4g.example.client.company.CompanyEventFilter" />
	</filters>
	<eventHandlers package="com.mvp4g.example.client.company.handler">
		<eventHandler name="handler1" class="CompanyListHandler"
			services="service" />
		<eventHandler name="handler2" class="CompanyListHandler"
			services="service" />
	</eventHandlers>

	<childModules package="com.mvp4g.example.client"
		beforeEvent="beforeLoad" afterEvent="afterLoad" errorEvent="errorOnLoad">
		<childModule name="companyModule" class=".company.CompanyModule"
			eventToDisplayView="changeBody" />
		<childModule name="productModule" class=".product.ProductModule"
			async="false" autoLoad="false" />
	</childModules>

	<views package="com.mvp4g.example.client.view">
		<view name="rootView" class="com.mvp4g.util.test_tools.RootView" />
		<view name="userCreateView" class="UserCreateView" />
		<view name="userDisplayView" class=".display.UserDisplayView" />
	</views>

	<services package="com.mvp4g.example.client.services">
		<service name="userService" class="UserService" path="/service/user" />
		<service name="userRpcService" class="com.mvp4g.example.client.rpc.UserService" />
		<service name="userDisplayService" class=".display.UserService" />
	</services>

	<presenters package="com.mvp4g.example.client.presenter">
		<presenter name="rootPresenter" class="com.mvp4g.util.test_tools.RootPresenter"
			view="rootView" />
		<presenter name="createUserPresenter" class="UserCreatePresenter"
			view="userCreateView" services="userService" />
		<presenter name="displayUserPresenter" class=".display.UserDisplayPresenter"
			view="userDisplayView" />
	</presenters>

	<history package="com.mvp4g.example.client.history" initEvent="init"
		notFoundEvent="event404">
		<converter name="userConverter" class=".display.UserHistoryConverter"
			services="userService" />
		<converter name="stringConverter" class="StringHistoryConverter"
			services="" />
		<converter name="particularConverter"
			class="com.mvp4g.example.client.StringHistoryConverter" />
	</history>


	<events>
		<event type="userCreated" calledMethod="onUserCreated"
			eventObjectClass="com.mvp4g.example.client.bean.UserBean" handlers="displayUserPresenter" />
		<event type="userDisplay" calledMethod="onUserDisplay"
			eventObjectClass="com.mvp4g.example.client.bean.UserBean" handlers="displayUserPresenter"
			history="userConverter" />
		<event type="changeBody" calledMethod="onChangeBody" handlers="rootPresenter"
			eventObjectClass="com.mvp4g.example.client.view.widget.Page" />
		<event type="displayMessage" calledMethod="onDisplayMessage"
			handlers="rootPresenter" history="stringConverter" />
		<event type="start" calledMethod="onStart" handlers="rootPresenter" />
		<event type="init" handlers="rootPresenter" />
		<event type="event404" handlers="rootPresenter" />
		<event type="beforeLoad" handlers="rootPresenter" />
		<event type="afterLoad" handlers="rootPresenter" />
		<event type="errorOnLoad" handlers="rootPresenter" />
		<event type="optionalEvent" handlers="" />
	</events>

	<start view="rootView" eventType="start" history="true" />
</mvp4g>

=== bubu03/mvp4g/examples/Mvp4gModulesXml/src/xmlConfig/company-mvp4g.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<mvp4g xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://mvp4g.googlecode.com/svn/trunk/xsd/mvp4g-conf.xsd">
	<debug logLevel="DETAILED" />
	<filters afterHistory="true" filterForward="false">
		<filter name="companyEventFilter"
			class="com.mvp4g.example.client.company.CompanyEventFilter" />
	</filters>
	<history package="com.mvp4g.example.client.company.historyConverter">
		<converter name="companyHC" class="CompanyHistoryConverter" />
		<converter name="companyCreationHC" class="CompanyCreationHistoryConverter"
			convertParams="false" />
	</history>
	<eventHandlers package="com.mvp4g.example.client.company.handler">
		<eventHandler name="listHandler" class="CompanyListHandler"
			services="service" />
	</eventHandlers>
	<views package="com.mvp4g.example.client.company.view">
		<view name="listView" class="CompanyListView" />
		<view name="displayView" class="CompanyDisplayView" />
		<view name="editView" class="CompanyEditView" />
		<view name="creationView" class="CompanyCreationView" />
		<view name="selectorView" class="CompanyNameSelectorView" />
		<view name="rowView" class="CompanyRowView" />
	</views>
	<services package="com.mvp4g.example.client.company">
		<service name="service" class="CompanyService" />
	</services>
	<presenters package="com.mvp4g.example.client.company.presenter">
		<presenter name="listPresenter" class="CompanyListPresenter"
			view="listView" />
		<presenter name="displayPresenter" class="CompanyDisplayPresenter"
			view="displayView" services="service" />
		<presenter name="editPresenter" class="CompanyEditPresenter"
			view="editView" services="service" />
		<presenter name="creationPresenter" class="CompanyCreationPresenter"
			view="creationView" services="service" />
		<presenter name="selectorPresenter" class="CompanyNameSelectorPresenter"
			view="selectorView" />
		<presenter name="rowPresenter" view="rowView" class="CompanyRowPresenter"
			multiple="true" services="service" />
	</presenters>
	<events>
		<event type="forward" handlers="listPresenter" />
		<event type="goToCompany" handlers="listPresenter" activate="rowPresenter"
			deactivate="creationPresenter, displayPresenter, editPresenter" />
		<event type="goToList" handlers="listPresenter" activate="rowPresenter"
			deactivate="creationPresenter, displayPresenter, editPresenter" />
		<event type="goToCreation" handlers="creationPresenter"		             
			activate="creationPresenter" deactivate="editPresenter, displayPresenter, rowPresenter"
			history="companyCreationHC" historyName="create" />
		<event type="goToEdit" handlers="editPresenter" activate="editPresenter"
			deactivate="creationPresenter, displayPresenter, rowPresenter" />
		<event type="goToDisplay" handlers="displayPresenter" history="companyHC"
			activate="displayPresenter" deactivate="editPresenter, creationPresenter, rowPresenter"
			historyName="" />
		<event type="displayMessage" forwardToParent="true"
			eventObjectClass="java.lang.String" />
		<event type="changeBody" eventObjectClass="com.google.gwt.user.client.ui.Widget"
			forwardToParent="true" />
		<event type="companyCreated" handlers="listPresenter, displayPresenter"
			activate="displayPresenter" deactivate="editPresenter" />
		<event type="companyUpdated" handlers="rowPresenter" activate="rowPresenter"
			deactivate="creationPresenter, displayPresenter, editPresenter" />
		<event type="companyDeleted" handlers="listPresenter" />
		<event type="selectCompanyMenu" forwardToParent="true"
			eventObjectClass="" />
		<event type="nameSelected"
			handlers="displayPresenter, editPresenter, creationPresenter, rowPresenter" />
		<event type="displayNameSelector" handlers="selectorPresenter" />
		<event type="companyListRetrieved" handlers="listPresenter" />
		<event type="getCompanyList" handlers="listHandler" />
	</events>

	<start view="listView" forwardEventType="forward" />

</mvp4g>

=== bubu03/mvp4g/examples/Mvp4gModulesXml/src/mvp4g-conf.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<mvp4g xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mvp4g.googlecode.com/svn/tags/mvp4g-1.1.0/xsd/mvp4g-conf.xsd">

    <debug logLevel="SIMPLE" logger="com.mvp4g.example.client.main.CustomLogger" />
	
	<ginModule class="com.mvp4g.example.client.Mvp4gGinModule" />	

	<childModules package="com.mvp4g.example.client" beforeEvent="beforeLoad" afterEvent="afterLoad" errorEvent="errorOnLoad">
		<childModule name="companyModule" class=".company.CompanyModule" eventToDisplayView="changeBody"/>
		<childModule name="productModule" class=".product.ProductModule" async="false" autoDisplay="false"/>	
	</childModules>
	<history package="com.mvp4g.example.client.main.historyConverter" initEvent="start">
		<converter name="menuHC" class="MenuHistoryConverter"/>
	</history>
	<views package="com.mvp4g.example.client.main" >
		<view name="rootView" class="MainView" />		
	</views>	
	<presenters package="com.mvp4g.example.client.main" >
		<presenter name="rootPresenter" class="MainPresenter" view="rootView" />		
	</presenters>
	<events>
		<event type="goToCompany" modulesToLoad="companyModule" history="menuHC" eventObjectClass="java.lang.Integer,java.lang.Integer" historyName="company"/>
		<event type="goToProduct" modulesToLoad="productModule" history="menuHC" eventObjectClass="java.lang.Integer,java.lang.Integer" />
		<event type="changeBody" handlers="rootPresenter" />
		<event type="errorOnLoad" handlers="rootPresenter" />
		<event type="beforeLoad" handlers="rootPresenter"/>
		<event type="afterLoad" handlers="rootPresenter"/>
		<event type="displayMessage" handlers="rootPresenter"/>
		<event type="start" />		
		<event type="selectCompanyMenu" handlers="rootPresenter"/>
		<event type="selectProductMenu" handlers="rootPresenter"/>		
	</events>
	
	<start view="rootView" history="true"/>
	
</mvp4g>

=== bubu03/mvp4g/examples/Mvp4gModulesXml/src/xmlConfig/product-mvp4g.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<mvp4g xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mvp4g.googlecode.com/svn/tags/mvp4g-1.1.0/xsd/mvp4g-conf.xsd">
	<filters>
		<filter name="productEventFilter" class="com.mvp4g.example.client.product.presenter.ProductListPresenter" />
	</filters>
	<history package="com.mvp4g.example.client.product.historyConverter">
		<converter name="productHC" class="ProductHistoryConverter"/>
	</history>
	<views package="com.mvp4g.example.client.product.view" >
		<view name="listView" class="ProductListView" />
		<view name="displayView" class="ProductDisplayView"/>
		<view name="editView" class="ProductEditView"/>
		<view name="creationView" class="ProductCreationView"/>
	</views>
	<services package="com.mvp4g.example.client.product" >
		<service name="service" class="ProductService" />
	</services>
	<presenters package="com.mvp4g.example.client.product.presenter" >
		<presenter name="listPresenter" class="ProductListPresenter" view="listView" services="service" />
		<presenter name="displayPresenter" class="ProductDisplayPresenter" view="displayView" services="service" />
		<presenter name="editPresenter" class="ProductEditPresenter" view="editView"  services="service" />			
		<presenter name="creationPresenter" class="ProductCreationPresenter" view="creationView"  services="service" />
	</presenters>
	<events>
		<event type="goToProduct" handlers="listPresenter" />
		<event type="goToCreation" handlers="creationPresenter" />
		<event type="goToEdit" handlers="editPresenter" />
		<event type="goToDisplay" handlers="displayPresenter" history="productHC"/>
		<event type="changeBody" eventObjectClass="com.google.gwt.user.client.ui.Widget" forwardToParent="true"/>
		<event type="displayMessage" eventObjectClass="java.lang.String" forwardToParent="true"/>
		<event type="productCreated" handlers="listPresenter, displayPresenter"/>
		<event type="productDeleted" handlers="listPresenter"/>
		<event type="selectProductMenu" forwardToParent="true" eventObjectClass=""/>		
	</events>
	
	<start view="listView" />
	
</mvp4g>
